project_id = "fsnjwooppfqmiszxfidn"

[functions.gmail-auth]
verify_jwt = false

[functions.gmail-scan]
verify_jwt = true

[functions.ocr-extract]
verify_jwt = true

[functions.structure-invoice]
verify_jwt = true